In [2]:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.".split(".")

['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
 ' Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
 ' Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',
 ' Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
 '']

### Bag of words

In [1]:
import numpy as np
import pandas as pd

In [4]:

df = pd.DataFrame({"text":["Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                         "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                         "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
                          "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"],"output":[1,1,0,0]})
df

text  output
0  Lorem ipsum dolor sit amet, consectetur adipis...       1
1  Ut enim ad minim veniam, quis nostrud exercita...       1
2  Duis aute irure dolor in reprehenderit in volu...       0
3  Excepteur sint occaecat cupidatat non proident...       0

In [5]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:

bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'lorem': 38, 'ipsum': 33, 'dolor': 15, 'sit': 55, 'amet': 4, 'consectetur': 9, 'adipiscing': 1, 'elit': 20, 'sed': 53, 'do': 14, 'eiusmod': 19, 'tempor': 57, 'incididunt': 32, 'ut': 59, 'labore': 35, 'et': 24, 'dolore': 16, 'magna': 39, 'aliqua': 2, 'enim': 21, 'ad': 0, 'minim': 40, 'veniam': 61, 'quis': 51, 'nostrud': 44, 'exercitation': 28, 'ullamco': 58, 'laboris': 36, 'nisi': 42, 'aliquip': 3, 'ex': 26, 'ea': 18, 'commodo': 8, 'consequat': 10, 'duis': 17, 'aute': 6, 'irure': 34, 'in': 31, 'reprehenderit': 52, 'voluptate': 62, 'velit': 60, 'esse': 22, 'cillum': 7, 'eu': 25, 'fugiat': 29, 'nulla': 45, 'pariatur': 48, 'excepteur': 27, 'sint': 54, 'occaecat': 46, 'cupidatat': 12, 'non': 43, 'proident': 49, 'sunt': 56, 'culpa': 11, 'qui': 50, 'officia': 47, 'deserunt': 13, 'mollit': 41, 'anim': 5, 'id': 30, 'est': 23, 'laborum': 37}


In [8]:
bow.toarray()

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [9]:

print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1
  0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0]]
[[1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0
  1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 2 0 1 0]]
[[0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 2 0 0 1 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1]]


In [10]:
cv.transform(['Lorem ipsum dolor sit amet,in reprehenderit in voluptate sint occaecat cupidatat']).toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1]],
      dtype=int64)

### N-grams

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [13]:
bow_n_gram = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'lorem ipsum': 39, 'ipsum dolor': 35, 'dolor sit': 14, 'sit amet': 55, 'amet consectetur': 3, 'consectetur adipiscing': 8, 'adipiscing elit': 1, 'elit sed': 20, 'sed do': 53, 'do eiusmod': 12, 'eiusmod tempor': 19, 'tempor incididunt': 57, 'incididunt ut': 34, 'ut labore': 61, 'labore et': 37, 'et dolore': 24, 'dolore magna': 16, 'magna aliqua': 40, 'ut enim': 60, 'enim ad': 21, 'ad minim': 0, 'minim veniam': 41, 'veniam quis': 63, 'quis nostrud': 51, 'nostrud exercitation': 45, 'exercitation ullamco': 28, 'ullamco laboris': 58, 'laboris nisi': 38, 'nisi ut': 43, 'ut aliquip': 59, 'aliquip ex': 2, 'ex ea': 26, 'ea commodo': 18, 'commodo consequat': 7, 'duis aute': 17, 'aute irure': 5, 'irure dolor': 36, 'dolor in': 13, 'in reprehenderit': 32, 'reprehenderit in': 52, 'in voluptate': 33, 'voluptate velit': 64, 'velit esse': 62, 'esse cillum': 22, 'cillum dolore': 6, 'dolore eu': 15, 'eu fugiat': 25, 'fugiat nulla': 29, 'nulla pariatur': 46, 'excepteur sint': 27, 'sint occaecat': 54, 'oc

In [15]:
print(bow_n_gram[0].toarray())
print(bow_n_gram[1].toarray())
print(bow_n_gram[2].toarray())

[[0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1
  0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0]]
[[1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0
  0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0]]
[[0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0
  1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1]]


### TF-IDF (Term frequency- Inverse document frequency)

In [17]:

from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [18]:
arr = tfid.fit_transform(df['text']).toarray()

In [19]:

arr

array([[0.        , 0.23659262, 0.23659262, 0.        , 0.23659262,
        0.        , 0.        , 0.        , 0.        , 0.23659262,
        0.        , 0.        , 0.        , 0.        , 0.23659262,
        0.18653234, 0.18653234, 0.        , 0.        , 0.23659262,
        0.23659262, 0.        , 0.        , 0.        , 0.23659262,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.23659262, 0.23659262, 0.        ,
        0.23659262, 0.        , 0.        , 0.23659262, 0.23659262,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.23659262, 0.        ,
        0.23659262, 0.        , 0.23659262, 0.        , 0.18653234,
        0.        , 0.        , 0.        ],
       [0.23913886, 0.        , 0.        , 0.23913886, 0.        ,
        0.        , 0.        , 0.        , 0.23913886, 0.        ,
   

In [20]:

print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.51082562 1.51082562 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.51082562
 1.91629073 1.91629073 1.91629073]
